### ISSUE TITLE
Invalid use of licence

### ISSUE THREAD

**Issue by droidekas** [vishal259/EasyLocation#2]
As per the `Apache 2.0 licence`, any derived work needs to be properly attributed before redistributing .Since this is taken from [akhgupta/Android-EasyLocation](https://github.com/akhgupta/Android-EasyLocation), I only see a new copyright name 

`Copyright 2016 Vishal Sojitra` . This is in violation of the Apache 2.0 licence as mentioned 
[here](http://www.apache.org/foundation/license-faq.html#WhatDoesItMEAN)

This also brings into picture the [weapplinse/EasyLocation](https://github.com/weapplinse/EasyLocation) which  as an organization is violating this licence.Please do the needful  or a DMCA notice can be issued for the same . 

Kindly add the attribution for the same.

This also holds true for all those who have forked this repo since the parent repo is participating in copyright infringement, namely:
@weapplinse
@FirmanMFK
@msoftware
@gadaramaulik123
@vorabhai
@indiascope
@morristech

**Comment by vorabhai** [comment]
How cand delete or unfork this project Sir..
I have no idea to how to unfrok ...
I wanna really no whats u say in this project ...
i wanna just fork in ur project but i wanna no use this project in any for use..

"How can unfrok this project i wanna done my work for unfrok this project."

**Comment by indiascope** [comment]
For Delete your Fork repo please follow this link:

Deleting fork repo  it will not effect to the original project. Editing and deleteing  it will only effect your fork on your repo page.

http://stackoverflow.com/questions/11302639/delete-forked-repo-from-github

**Comment by vorabhai** [comment]
Thanx Sir, Its a very good information above for this link....
Very very thanx..

**Comment by FirmanMFK** [comment]
Done
